<a href="https://colab.research.google.com/github/WanWin04/Colab_Notebook/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

In [2]:
import numpy as np

**Creating Numpy Arrays from Python Lists**

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
[3.14,4,2,3]

[3.14, 4, 2, 3]

In [5]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [6]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [8]:
a1 = np.array([1, 2, 3, 4])
type(a1)

numpy.ndarray

In [11]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
type(a2)

numpy.ndarray

In [12]:
a2.shape

(2, 3)

In [13]:
a2.ndim

2

In [14]:
a2.dtype

dtype('int64')

In [15]:
a2.size

6

**Creating Numpy Arrays from Scratch**

In [17]:
np.zeros([2, 4], dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
np.ones([2, 4], dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [22]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
np.full([3, 5], 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [24]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
np.random.random((4, 4))

array([[0.00125347, 0.5474757 , 0.05313992, 0.98300212],
       [0.38217637, 0.63767068, 0.77221353, 0.52469414],
       [0.16785781, 0.43636709, 0.04069901, 0.39387987],
       [0.07712396, 0.47508942, 0.38212186, 0.20905762]])

In [29]:
np.random.seed(0)
np.random.normal(0, 1, (3, 3))

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885]])

In [30]:
np.random.randint(0, 10, (3, 3))

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9]])

In [31]:
np.random.rand(4, 4)

array([[0.64817187, 0.36824154, 0.95715516, 0.14035078],
       [0.87008726, 0.47360805, 0.80091075, 0.52047748],
       [0.67887953, 0.72063265, 0.58201979, 0.53737323],
       [0.75861562, 0.10590761, 0.47360042, 0.18633234]])